version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: backend-db-container
    environment:
      POSTGRES_USER: backend-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: